// c:\Codes\gastdash.github.io\gastdash_website_flutter\lib\core\constants.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'text_styles.dart';